version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: yooini_db
    environment:
      POSTGRES_DB: yooini_03
      POSTGRES_USER: yooini_user
      POSTGRES_PASSWORD: yooini_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yooini_user -d yooini_03"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: yooini_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: yooini_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://yooini_user:yooini_password@db:5432/yooini_03
      - REDIS_URL=redis://redis:6379/0

  celery_worker:
    build: .
    container_name: yooini_celery_worker
    command: celery -A config worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://yooini_user:yooini_password@db:5432/yooini_03
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery_beat:
    build: .
    container_name: yooini_celery_beat
    command: celery -A config beat -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://yooini_user:yooini_password@db:5432/yooini_03
      - CELERY_BROKER_URL=redis://redis:6379/0

  flower:
    build: .
    container_name: yooini_flower
    command: celery -A config flower
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data: