# Generated by Django 5.1.5 on 2025-07-16 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('context_type', models.CharField(choices=[('workflow', '워크플로우 실행'), ('market_chat', '마켓 관리 대화'), ('product_analysis', '상품 분석'), ('support', '고객 지원'), ('system', '시스템 대화')], max_length=20)),
                ('messages', models.JSONField(default=list, help_text='대화 메시지 리스트')),
                ('metadata', models.JSONField(default=dict, help_text='추가 메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ttl_seconds', models.IntegerField(default=2592000, help_text='Time to live in seconds')),
                ('related_source_data', models.ManyToManyField(blank=True, help_text='이 대화와 관련된 소스 데이터', to='source_data.sourcedata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MemorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='대화 요약')),
                ('key_facts', models.JSONField(default=list, help_text='핵심 사실들')),
                ('decisions', models.JSONField(default=list, help_text='내려진 결정사항들')),
                ('action_items', models.JSONField(default=list, help_text='액션 아이템들')),
                ('embedding_id', models.CharField(blank=True, help_text='Upstash Vector DB의 임베딩 ID', max_length=100)),
                ('importance_score', models.FloatField(default=0.5, help_text='중요도 점수 (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to='context_management.conversationcontext')),
            ],
            options={
                'ordering': ['-importance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.CharField(db_index=True, max_length=100)),
                ('workflow_name', models.CharField(max_length=100)),
                ('input_context', models.JSONField(default=dict, help_text='입력 컨텍스트')),
                ('execution_context', models.JSONField(default=dict, help_text='실행 중 컨텍스트')),
                ('output_context', models.JSONField(default=dict, help_text='출력 컨텍스트')),
                ('learned_patterns', models.JSONField(default=dict, help_text='이 워크플로우에서 학습된 패턴들')),
                ('performance_metrics', models.JSONField(default=dict, help_text='실행 성능 메트릭')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_contexts', to='context_management.conversationcontext')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['context_type', 'created_at'], name='context_man_context_d937f3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationcontext',
            index=models.Index(fields=['user', 'is_active'], name='context_man_user_id_84cac1_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysnapshot',
            index=models.Index(fields=['importance_score', 'created_at'], name='context_man_importa_2f00e9_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowcontext',
            index=models.Index(fields=['workflow_name', 'created_at'], name='context_man_workflo_5b00f2_idx'),
        ),
    ]
