groups:
  # 애플리케이션 알림
  - name: application
    interval: 30s
    rules:
      # API 응답 시간
      - alert: SlowAPIResponse
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "API response time is slow"
          description: "95th percentile response time is {{ $value | humanizeDuration }} (threshold: 1s)"
          runbook_url: "https://wiki.company.com/runbooks/slow-api-response"

      # 에러율
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_request_total{status=~"5.."}[5m]))
            /
            sum(rate(http_request_total[5m]))
          ) > 0.05
        for: 5m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} (threshold: 5%)"
          runbook_url: "https://wiki.company.com/runbooks/high-error-rate"

      # 요청량 급증
      - alert: TrafficSpike
        expr: |
          rate(http_request_total[5m]) > 2 * 
          avg_over_time(rate(http_request_total[5m])[1h:5m] offset 5m)
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "Unusual traffic spike detected"
          description: "Request rate increased by {{ $value | humanizePercentage }}"

  # 시스템 리소스
  - name: system_resources
    interval: 30s
    rules:
      # CPU 사용률
      - alert: HighCPUUsage
        expr: |
          100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value | humanizePercentage }}"

      # 메모리 사용률
      - alert: HighMemoryUsage
        expr: |
          (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      # 디스크 공간
      - alert: LowDiskSpace
        expr: |
          (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
        for: 5m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Only {{ $value | humanizePercentage }} disk space left"

  # 데이터베이스
  - name: database
    interval: 30s
    rules:
      # 연결 수
      - alert: HighDatabaseConnections
        expr: pg_stat_database_numbackends{datname="dropship_prod"} > 180
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High number of database connections"
          description: "{{ $value }} active connections (limit: 200)"

      # 느린 쿼리
      - alert: SlowQueries
        expr: rate(pg_stat_statements_mean_time_seconds[5m]) > 1
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Slow database queries detected"
          description: "Average query time is {{ $value | humanizeDuration }}"

      # 데드락
      - alert: DatabaseDeadlocks
        expr: increase(pg_stat_database_deadlocks[5m]) > 0
        for: 1m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "Database deadlocks detected"
          description: "{{ $value }} deadlocks in the last 5 minutes"

  # Redis
  - name: redis
    interval: 30s
    rules:
      # 메모리 사용률
      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis is using {{ $value | humanizePercentage }} of allocated memory"

      # 연결 거부
      - alert: RedisRejectedConnections
        expr: increase(redis_rejected_connections_total[5m]) > 0
        for: 1m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "Redis is rejecting connections"
          description: "{{ $value }} connections rejected in the last 5 minutes"

  # 비즈니스 메트릭
  - name: business
    interval: 1m
    rules:
      # 주문 실패율
      - alert: HighOrderFailureRate
        expr: |
          (
            sum(rate(order_created_total{status="failed"}[15m]))
            /
            sum(rate(order_created_total[15m]))
          ) > 0.1
        for: 10m
        labels:
          severity: critical
          team: business
        annotations:
          summary: "High order failure rate"
          description: "{{ $value | humanizePercentage }} of orders are failing"

      # 결제 실패
      - alert: PaymentProcessingFailures
        expr: |
          sum(rate(payment_processed_total{status="failed"}[15m])) > 5
        for: 5m
        labels:
          severity: critical
          team: business
        annotations:
          summary: "Payment processing failures"
          description: "{{ $value }} payment failures per minute"

      # 재고 부족
      - alert: LowInventory
        expr: |
          product_stock_quantity < product_stock_threshold
        for: 30m
        labels:
          severity: warning
          team: business
        annotations:
          summary: "Low inventory for product {{ $labels.product_name }}"
          description: "Stock: {{ $value }}, SKU: {{ $labels.sku }}"

  # 보안
  - name: security
    interval: 30s
    rules:
      # 로그인 실패
      - alert: HighLoginFailureRate
        expr: |
          sum(rate(auth_login_attempts_total{status="failed"}[5m])) > 10
        for: 5m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "High login failure rate"
          description: "{{ $value }} failed login attempts per second"

      # 의심스러운 활동
      - alert: SuspiciousActivity
        expr: |
          sum by (ip_address) (rate(http_request_total[5m])) > 100
        for: 2m
        labels:
          severity: critical
          team: security
        annotations:
          summary: "Suspicious activity from IP {{ $labels.ip_address }}"
          description: "{{ $value }} requests per second from single IP"

  # 인프라
  - name: infrastructure
    interval: 30s
    rules:
      # 컨테이너 재시작
      - alert: ContainerRestarting
        expr: |
          increase(container_restart_count[15m]) > 3
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "Container {{ $labels.container_name }} is restarting frequently"
          description: "Restarted {{ $value }} times in the last 15 minutes"

      # 서비스 다운
      - alert: ServiceDown
        expr: up{job=~"backend|frontend|postgres|redis"} == 0
        for: 1m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.instance }} has been down for more than 1 minute"

      # SSL 인증서 만료
      - alert: SSLCertificateExpiringSoon
        expr: |
          (probe_ssl_earliest_cert_expiry - time()) / 86400 < 30
        for: 1h
        labels:
          severity: warning
          team: devops
        annotations:
          summary: "SSL certificate expiring soon"
          description: "Certificate for {{ $labels.instance }} expires in {{ $value }} days"